runners:
  - name: cirun-gcp-runner
    cloud: gcp
    instance_type: n1-standard-4
    machine_image: projects/cirun-labs/global/images/cirun-runner-ubuntu24-20250722-1632
    region:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f
    labels:
      - cirun-runner
    extra_config:
      enableNestedVirtualization: true