name: Release Packer Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Go version
        id: go
        run: |
          if [ -f plugin/.go-version ]; then
            echo "version=$(cat plugin/.go-version)" >> $GITHUB_OUTPUT
          elif [ -f plugin/go.mod ]; then
            echo "version=$(grep '^go ' plugin/go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT
          else
            echo "version=1.21" >> $GITHUB_OUTPUT
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}